### ISSUE TITLE
Mobile version of filtered options results

### ISSUE THREAD

**Issue by icecicle04** [aimeecesler/dinner-decider#65]
Mobile version of filtered options populates ON TOP of where the filtered option would be selected currently. Place that below the filtered option if possible

**Comment by aimeecesler** [comment]
Couldn't make it happen without the page looking funky. Right now the results div is part of the same column as the one with the random button so in order to rearrange them you have to break it off into it's own nested column. Unfortunately because of the bulma set-up, this way left a weird gap on the desktop site. Not sure if we still want to do it or not?
